<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-heading">
                <h4>Página de Inicio</h4>
                <div class="options">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#domshortcuttiles"><i class="fa fa-dashboard"></i></a></li>
                        <li><a data-toggle="tab" href="#codeshortcuttiles"><i class="fa fa-code"></i></a></li>
                    </ul>
                </div>

            </div>
            <div class="panel-body">        
                <div class="tab-content">
                    <div id="domshortcuttiles" class="tab-pane active">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                <label class="col-xs-1 control-label">Actualizado de:</label>
                                    <div class="col-xs-3">
                                        <input type="text" name="fecha1" id="fecha1" class="form-control" readonly>
                                    </div>
                                    <div class="col-xs-1">
                                        a
                                    </div>
                                    <div class="col-xs-3">
                                        <input type="text" name="fecha2" id="fecha2" class="form-control" readonly>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                <label class="col-xs-1 control-label">Busqueda:</label>
                                    <div class="col-xs-3">
                                        <input type="text" name="fecha_inicio" id="fecha_inicio" class="form-control" data-date-format="dd-mm-yyyy" placeholder="Fecha Inicial (dd-mm-YYYY)" required>
                                </div>
                                    <div class="col-xs-1">
                                        a
                                    </div>
                                    <div class="col-xs-3">
                                        <input type="text" name="fecha_fin" id="fecha_fin" class="form-control"  data-date-format="dd-mm-yyyy" placeholder="Fecha Final (dd-mm-YYYY)" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                <label class="col-xs-1 control-label">Ubicación:</label>
                                    <div class="col-xs-3">
                                        <input type="text" name="ubicacion" id="ubicacion" class="form-control">
                                    </div>
                                
                                <label class="col-xs-1 control-label">Sector:</label>
                                    <div class="col-xs-3">
                                        <input type="text" name="sector" id="sector" class="form-control">
                                    </div>
                                
                                <label class="col-xs-1 control-label">Tipo:</label>
                                    <div class="col-xs-3">
                                        <input type="text" name="tipo" id="tipo" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <h5>CARACTERISTICAS A BUSCAR</h5>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-2">
                                <input type="text" name="caracteristica1" id="caracteristica1" class="form-control" placeholder="Caracteristica 1">
                            </div>
                            <div class="col-xs-2">
                                <input type="text" name="caracteristica2" id="caracteristica2" class="form-control" placeholder="Caracteristica 2">
                            </div>
                            <div class="col-xs-2">
                                <input type="text" name="caracteristica3" id="caracteristica3" class="form-control" placeholder="Caracteristica 3">
                            </div>
                            <div class="col-xs-2">
                                <input type="text" name="caracteristica4" id="caracteristica4" class="form-control" placeholder="Caracteristica 4">
                            </div>
                            <div class="col-xs-2">
                                <input type="text" name="caracteristica5" id="caracteristica5" class="form-control" placeholder="Caracteristica 5">
                            </div>
                            <div class="col-xs-2">
                                <div class="pull-right">
                                <button class="btn btn-sm btn-primary" type="button" id="definir_pp"><i class="fa fa-plus fa-fw"></i>Ejecutar Filtro</button>
                                                             </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div id="jqxgrid" style="height: 550px; width: 100%;" ></div>
                            </div>
                        </div>

                    </div>
                    <div id="codeshortcuttiles" class="tab-pane">

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<style type="text/css">
                    .datepicker{
                        z-index:1151 !important;
                    }
                </style>
